








### register user
POST {{baseUrl}}/api/register
Content-Type: multipart/form-data; boundary=boundary
Authorization: 'Bearer {{token}}'

--boundary
Content-Disposition: form-data; name="file"; filename="my_image.jpg"
Content-Type: image/jpeg

< /Users/anel-bou/Desktop/abc.jpg>
--boundary
Content-Disposition: form-data; name="file"; filename="my_image.jpg"
Content-Type: image/jpeg

    {
        "FirstName": "Hi One",
        "LastName": "User",
        "LoginName": "abcdef",
        "Password":"ATest@123",
        "EmailAddress": "hello12@gmail.com",
        "MobileNo":"8220370001",
        "Address":"Test Address",
        "City":"Test City",
        "State":"Test State",
        "Country":"Test Country",
        "PinCode":"600050",
        "DOB":"2000/01/01",

    }



### login user
POST  {{baseUrl}}/api/login     
Content-Type: application/json


    {
        "MobileNo": "82203736s66",
        "Password": "admin@123"
    }
    






