








### register user
POST {{baseUrl}}/api/register
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="MobileNo"

8220373777
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Password"

admin@123
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="FirstName"

Ganesh
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="LastName"

DineshPrabhu
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="LoginName"

DineshShankary
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="EmailAddress"

atest1234ss67sai@gmail.uk
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Address"

Test Addressing
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Country"

Test Countrying
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="State"

Kerala
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Location"

143462223,793793
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="DoorNumber"

Test DoorNumbering
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Street"

Test StreetNameing
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Landmark"

Test Landmarking
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Area"

Test Areaing
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="City"

Test Citying
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Gender"

Male
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="FullName"

Ganga
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="abc.jpg"
Content-Type: image/jpg

< ./abc.jpg
--WebKitFormBoundary7MA4YWxkTrZu0gW--





### login user
POST  {{baseUrl}}/api/login     
Content-Type: application/json

    {
        "MobileNo": "9750022933",
        "Password": "Asdf@123$"
    }
    






