

GET {{baseUrl}}

### get all employees

GET {{baseUrl}}/api/employees
Authorization: Bearer {{token}}

   

### get employee by id
GET {{baseUrl}}/api/employees/22
Authorization: Bearer {{token}}

### create employee
POST {{baseUrl}}/api/employees
Content-Type: multipart/form-data
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

    {
    "FirstName": "John Doe",
    "LastName": "Doe",
    "MobileNo": "9750022931",
    "Title": "Mr"
    }

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="t"

{{@./public/upload/test.png}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="dp.png"
Content-Type: image/png

< testtitle
------WebKitFormBoundary7MA4YWxkTrZu0gW--

    

### update employee

PUT {{baseUrl}}/api/employees/26
Content-Type: application/json
Authorization: Bearer {{token}}

    {
    "FirstName": "John Doe Gebran",
    "LastName": "Doe",
    "MobileNo": "9750022911",
    "Title": "Mr",
    "CreatedGUID": 1
    }

### delete employee
DELETE {{baseUrl}}/api/employees/26
Authorization: Bearer {{token}}




