
### getAllProductCategories
GET {{baseUrl}}/api/productCategories
Content-Type: application/json
Authorization: Bearer {{token}}

### getProductCategoryByProductCategoryGUID

GET {{baseUrl}}/api/productCategories/1
Content-Type: application/json
Authorization: Bearer {{token}}

### createProductCategory
POST {{baseUrl}}/api/productCategories
Content-Type: application/json
Authorization: Bearer {{token}}

    {

        "ProductCategoryName": "test-1"
    }

### updateProductCategoryByProductCategoryGUID

PUT {{baseUrl}}/api/productCategories/8
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "ProductCategoryName": "test"
    }

### deleteProductCategoryByProductCategoryGUID

DELETE {{baseUrl}}/api/productCategories/8
Content-Type: application/json
Authorization: Bearer {{token}}





