### getAllProductMasters

GET {{baseurl}}/productmasters
Content-Type: application/json
Authorization: Bearer {{token}}


### getAllProductMasterById
GET {{baseurl}}/productmasters/1
Content-Type: application/json
Authorization: Bearer {{token}}

### createProductMaster
POST {{baseurl}}/productmasters
Content-Type: application/json
Authorization: Bearer {{token}}

    {
     "ProductID": "ABC122",
     "ProductName": "string",
     "ProductCode": "string",
     "ProductCategoryGUID": 0,
     "ProductSubCategoryGUID": 0,
     "Unit_Price": 0,
     "MRP": 0,
     "GST": 0,
     "Qty": 0,
     "UnitsInStock": 0,
     "IsActive": 0,
     "CreatedGUID": 0,
     "CreatedDate": "2020-05-06T12:00:00.000Z",
     "SKU": "string",
     "UOM": "string",
     "UOMTypeGUID": 0
    
    }

### updateProductMaster
PUT {{baseurl}}/productmasters/10
Content-Type: application/json
Authorization: Bearer {{token}}

   {
    "ProductID": 1,
    "ProductName": "stringABC",
    "ProductCode": "ProductCode",
    "ProductCategoryGUID": 1,
    "ProductSubCategoryGUID": 1,
    "Unit_Price": 100,
    "MRP": 100,
    "GST": 3,
    "Qty": 1,
    "UnitsInStock": 10,
    "IsActive": 1,
    "CreatedGUID": 1,
    "CreatedDate": "2020-05-06T12:00:00.000Z",
    "SKU": "string1",
    "UOM": "string1",
    "UOMTypeGUID": 1

   }

### deleteProductMaster
DELETE {{baseurl}}/productmasters/11
Content-Type: application/json
Authorization: Bearer {{token}}



