
### getAllProductCategories
GET {{{{baseurl}}}}/api/productCategories
Content-Type: application/json
Authorization: Bearer {{token}}

### getProductCategoryByProductCategoryGUID

GET {{{{baseurl}}}}/api/productCategories/1
Content-Type: application/json
Authorization: Bearer {{token}}

### createProductCategory
POST {{{{baseurl}}}}/api/productCategories
Content-Type: application/json
Authorization: Bearer {{token}}

    {

        "ProductCategoryName": "test-1"
    }

### updateProductCategoryByProductCategoryGUID

PUT {{{{baseurl}}}}/api/productCategories/8
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "ProductCategoryName": "test"
    }

### deleteProductCategoryByProductCategoryGUID

DELETE {{{{baseurl}}}}/api/productCategories/8
Content-Type: application/json
Authorization: Bearer {{token}}





