### getAllProductSubCategories

GET {{{{baseurl}}}}/api/productSubCategories
Content-Type: application/json
Authorization: Bearer {{token}}

### getProductSubCategory
GET {{{{baseurl}}}}/api/productSubCategories/10
Content-Type: application/json
Authorization: Bearer {{token}}

### createProductSubCategory
POST {{{{baseurl}}}}/api/productSubCategories
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        
        "ProductSubCategoryName":"test category"
    }
   
### updateProductSubCategory
PUT {{{{baseurl}}}}/api/productSubCategories/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "string",
    "description": "string",
    "productCategoryId": 0
}
