### getAllStoreMasters
GET {{baseUrl}}/api/storeMasters
Content-Type: application/json
Authorization: Bearer {{token}}

### getStoreMaster
GET {{baseUrl}}/api/storeMasters/1
Content-Type: application/json
Authorization: Bearer {{token}}

### createStoreMaster
POST {{baseUrl}}/api/storeMasters
Content-Type: application/json
Authorization: Bearer {{token}}

{

    "StoreID": "S0002",
    "StoreName": "Tamil Dairy",
    "Phone": "099-1212",
    "Email": "S0001.tamildairy@gmail.com",
    "Address": "Anna Nagar",
    "City": "Chennai",
    "State": "Tamil nadu",
    "PinCode": "600040",
    "GSTNO": "GSTIN12121218",
    "CreatedDate": "2023-02-23T22:27:20.406Z",
    "ModifiedDate": null,
    "DeletedDate": null
}

### updateStoreMaster
PUT  {{baseUrl}}/api/storeMasters/1
Content-Type: application/json
Authorization: Bearer {{token}}

{


    "StoreName": "Tamil Dairy",
    "Phone": "099-1212",
    "Email": "S0001.tamildairy@gmail.com",
    "Address": "Anna Nagar",
    "City": "Chennai",
    "State": "Tamil nadu",
    "PinCode": "600040",
    "GSTNO": "GSTIN12121219"
  
}

### deleteStoreMaster
DELETE {{baseUrl}}/api/storeMasters/1
Content-Type: application/json
Authorization: Bearer {{token}}


