######  getAllUsers()

GET {{baseUrl}}/api/users
Content-Type: application/json
Authorization:  Bearer {{token}}


### getUserById()
GET {{baseUrl}}/api/users/1
Content-Type: application/json
Authorization:  Bearer {{token}}


###updateUserById()
PUT {{baseUrl}}/api/users/8220370001
Content-Type: application/json
Authorization:  Bearer {{token}}
    
    {
        "FirstName": "Testing",
        "LastName": "Usering",
        "LoginName": "Atest1234567812",
        "Password":"Asdf@1231",
        "EmailAddress": "atest1234567i@gmail.com",

        "Address":"Test Addressing",
        "City":"Test Citying",
        "State":"Test Stateing",
        "Country":"Test Countrying",
        "PinCode":"600050",
        "State":"Tamilnadu",
        "City":"Chennai",
        "Location":"143462223,793793",
        "DoorNumber":"Test DoorNumbering",
        "Street":"Test StreetNameing",
        "Landmark":"Test Landmarking",
        "Area":"Test Areaing",
        "City":"Test Citying"

     
    }

### deleteUserById()
DELETE {{baseUrl}}/api/users/8220373888
Content-Type: application/json
Authorization:  Bearer {{token}}




